###############################################################################################
#                                                                                             #
# This file is used to control the AppVeyor build for the PSDesiredStateConfiguration Project #
#                                                                                             #
#                                                                                             #
###############################################################################################

version: 0.4.0.{build}
    
branches:
  only:
    - master    

# Having a build cache is a workaround to prevent DSC builds from failing when Appveyor has issues with downloading .NETCore or Nuget packages.
# The Nuget package cache here will be updated whenever a .csproj file changes (from the last build) as that's what may trigger a change in Nuget package dependency
# More documentation on build cache - https://www.appveyor.com/docs/build-cache/
cache:  
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> **\cs.proj'

init:
  - ps: |
      # Uncomment to enable RDP during init
      # We cannot use any DscEngineering function here as the repository is cloned after init

      #$blockRdp = $true
      #iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

nuget:
  project_feed: true

# Only build the standard image
environment:  
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 # This is the standard AppVeyor image

build: off

install:
  - ps: |
      git config --global url.git@github.com:.insteadOf https://github.com/  
      Import-Module $env:APPVEYOR_BUILD_FOLDER\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1
      
on_finish:
  - ps: |
      Write-Output "Hello"

notifications:
  - provider: Email
    to:
    - insivara@microsoft.com
    on_build_success: true
